###############################################################
#
## Copyright (Â©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated: 23-OCT-2025 1200Z by David Hoyt
#
## Intent: WinCmake testing / build
#
## TODO: Add Unit Test Suite
#
#
#
#
#
#
#
#
#
###############################################################

name: 23102005-win

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        build_type: [Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          git clone https://github.com/InternationalColorConsortium/iccDEV.git
          cd iccDEV

      - name: Configure
        run: |
          cd iccDEV
          cmake --preset vs2022-x64 -B build -S Build/Cmake ^
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ^
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          dir build

      - name: Build project
        run: |
          cd iccDEV
          cmake --build build --config ${{ matrix.build_type }}
          dir build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iccdev-v231-windows-${{ matrix.build_type }}
          path: |
            iccDEV/build/**/*.lib
            iccDEV/build/**/*.a
            iccDEV/build/**/*.dll
            iccDEV/build/**/*.exe
            iccDEV/build/**/*.pdb
            iccDEV/Testing/**/*
            iccDEV/LICENSE.md
            iccDEV/README.md            
            iccDEV/docs/**
          if-no-files-found: warn
