###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated:09-NOV-2025 at 1100Z by David Hoyt (©)
#
## Intent: linter * code checks
#
## TODO: 
#
#
###############################################################

name: "lint"
permissions:
  contents: read
  
on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Lint on ${{ matrix.ubuntu }}
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [ubuntu-latest]

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Git anonymous identity
    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake clang git python3 curl unzip tar \
          libxml2-dev libtiff-dev nlohmann-json3-dev libjpeg-dev libpng-dev \
          libtool m4 autoconf automake libltdl-dev libx11-dev libxft-dev \
          libxext-dev libxi-dev libxtst-dev libxrandr-dev autoconf autoconf-archive automake libtool cppcheck clang-format clang-tidy
    # Clone DemoIccMAX repository and checkout vcpkg branch
    - name: lint & code checks
      run: |
       cppcheck --enable=warning,performance,portability --quiet --std=c++17 Tools/CmdLine/*/*.cpp
       cppcheck --enable=warning,performance,portability --quiet --std=c++17 IccProfLib/*.cpp
       cppcheck --enable=warning,performance,portability --quiet --std=c++17 IccProfLib/*.h
       cppcheck --enable=warning,performance,portability --quiet --std=c++17 IccXML/*/*.cpp
       cppcheck --enable=warning,performance,portability --quiet --std=c++17 IccXML/*/*.h
       clang-format $(find Tools/CmdLine -type f \( -name '*.cpp' -o -name '*.h' \))
    
  
