###############################################################
#
## Copyright (©) 2024-2025 David H Hoyt. All rights reserved.
##                 https://srd.cx
##
## Last Updated:05-AUGUST-2025 at 1100Z by David Hoyt (©)
#
## Intent: VCPKG-Ubu-mtx3
#
## TODO: 
#
#
###############################################################

name: "VCPKG Ubuntu Matrix"

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test Linux on Ubuntu ${{ matrix.ubuntu }}
    runs-on: ${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [ubuntu-22.04, ubuntu-latest]

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Git anonymous identity
    - name: Set up Git anonymous identity
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake clang git python3 curl unzip tar \
          libxml2-dev libtiff-dev nlohmann-json3-dev libjpeg-dev libpng-dev \
          libtool m4 autoconf automake libltdl-dev libx11-dev libxft-dev \
          libxext-dev libxi-dev libxtst-dev libxrandr-dev autoconf autoconf-archive automake libtool
    # Clone DemoIccMAX repository and checkout vcpkg branch
    - name: Clone DemoIccMAX repository
      run: |
       git clone https://github.com/InternationalColorConsortium/vcpkg.git
       cd vcpkg
       git checkout iccdev
       ./bootstrap-vcpkg.sh -disableMetrics
       ./vcpkg integrate install
       ./vcpkg install iccdev
       ./vcpkg/vcpkg list
  
